spring:
  application:
    name: quantity-measurement-app

  datasource:
    url: jdbc:mysql://database-1.czkykcsuyr06.ap-south-1.rds.amazonaws.com:3306/quantitymeasurementdb
    username: admin
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - profile
              - email

server:
  port: 8080

logging:
  level:
    root: INFO
    com.app.quantitymeasurement: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000

springdoc:
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

app:
  frontend:
    url: http://13.235.224.122